name: MLOPS G42 CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches : [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: pip install flake8
      - name: Lint code by running Flake8
        run: flake8 .
  
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: List files
        run: ls -R
      - name: Run tests
        run: python -m unittest discover -s tests -p "test_*.py"
  
  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Start Flask app
        run: |
          nohup python app.py &
          sleep 10 # Wait for the server to start
      - name: Test Flask app endpoints
        run: |
          echo "Testing /train endpoint..."
          curl -s http://localhost:5000/train
          
          echo "Testing /evaluate endpoint..."
          curl -s http://localhost:5000/evaluate
          
          echo "Testing /predict endpoint..."
          curl -s -X POST -H "Content-Type: application/json" -d '{"input": [5.1, 3.5, 1.4, 0.2]}' http://localhost:5000/predict